# -*- coding: utf-8 -*-
"""schema.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oq6Zl8r1SYARrJH8tMzNLo6-ON0wDVhN
"""

from pydantic import BaseModel
from typing import List, Dict

class Item(BaseModel):
    sku: str
    qty: int
    unit_cost: float
    margin_pct: float

class Client(BaseModel):
    name: str
    contact: str
    lang: str = "en"

class QuotationRequest(BaseModel):
    client: Client
    currency: str
    items: List[Item]
    delivery_terms: str
    notes: str = ""

class QuotationResponse(BaseModel):
    lines: List[Dict]
    grand_total: float
    email_draft: Dict[str, str]