# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EsM_-H_8krYXtih8xo8gbD4do5YUZSk8
"""

def calculate_quote(req):
    lines = []
    grand_total = 0.0
    for item in req.items:
        price_per_unit = item.unit_cost * (1 + item.margin_pct / 100)
        line_total = price_per_unit * item.qty
        lines.append({
            "sku": item.sku,
            "qty": item.qty,
            "price_per_unit": round(price_per_unit, 2),
            "line_total": round(line_total, 2)
        })
        grand_total += line_total
    return {"lines": lines, "grand_total": round(grand_total, 2)}

def generate_email(req, quote):
    # For now mock LLM
    en = f"Dear {req.client.name},\n\nPlease find our quotation attached. Total = {quote['grand_total']} {req.currency}. Delivery terms: {req.delivery_terms}. Notes: {req.notes}\n\nRegards"
    ar = f"عميلنا العزيز {req.client.name},\n\nيرجى الاطلاع على عرض السعر المرفق. المجموع = {quote['grand_total']} {req.currency}. شروط التسليم: {req.delivery_terms}. ملاحظات: {req.notes}\n\nمع التحية"
    return {"en": en, "ar": ar}